import { esc, icon } from './components.mjs';
const nav = [['/','Home'],['/menu/','Menu'],['/whats-on/',"What's On"],['/visit/','Visit']];
export function layout({site,page,title,description,main,head=''}) {
 const L=site.links;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#F6F2E8"><title>${esc(title==='Home'?'Find your Alibi':title)} · Alibi Incline Public House</title><meta name="description" content="${esc(description)}"><link rel="icon" href="/assets/favicon.png"><link rel="preload" href="/assets/fonts/fraunces-soft.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/fonts/dm-sans-var.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/site.css"><link rel="stylesheet" href="/assets/desktop.css" media="screen and (min-width: 1000px)">${head}<script src="/assets/site.js" defer></script><script src="/assets/desktop-story.js" defer></script></head><body data-page="${page}"><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><a class="brand${page==='home'?' brand-type':''}" href="/" aria-label="Alibi Incline Public House, home">${page==='home'?'<strong>Alibi</strong><span>INCLINE PUBLIC HOUSE</span>':'<img src="/assets/svg/alibi-wordmark.svg" width="102" height="58" alt="Alibi Ale Works"><span>INCLINE<br>PUBLIC HOUSE</span>'}</a><button class="nav-toggle" type="button" aria-label="Open navigation" aria-expanded="false" aria-controls="site-nav">Menu ${icon('menu')}</button><nav id="site-nav" aria-label="Main navigation">${nav.map(([href,label])=>`<a href="${href}"${(page==='home'&&href==='/')||href===`/${page}/`?' aria-current="page"':''}>${label}</a>`).join('')}<a class="nav-order" href="${L.order}" target="_blank" rel="noopener">Order pickup ${icon('arrow-ne')}<span class="sr-only"> (opens in a new tab)</span></a></nav></header>
<main id="main">${main}</main>
<footer class="site-footer"><div class="footer-top container"><a href="/" class="footer-logo"><img src="/assets/svg/alibi-footer-lockup.svg" width="245" height="164" alt="Alibi Ale Works"></a><div class="footer-address"><p class="eyebrow">INCLINE PUBLIC HOUSE</p><p>931 Tahoe Blvd.<br>Incline Village, NV 89451</p><a href="tel:${site.phone.tel}">${site.phone.display}</a></div><nav aria-label="Footer navigation">${nav.map(([href,label])=>`<a href="${href}">${label}</a>`).join('')}</nav><nav aria-label="More from Alibi"><a href="${L.giftCards}" target="_blank" rel="noopener">Gift cards ↗</a><a href="${L.events}" target="_blank" rel="noopener">Alibi’s calendar ↗</a><a href="${L.newsletter}" target="_blank" rel="noopener">The Alibi newsletter ↗</a><a href="${L.instagram}" target="_blank" rel="noopener">Instagram ↗</a></nav></div><div class="footer-bottom container"><p>A private design concept for Alibi Ale Works.</p><details class="credits"><summary>About this concept &amp; credits</summary><div><p>This is a design preview, not Alibi’s official website. For current menus, hours and events, follow the links to Alibi.</p><p>The illustrations are artistic interpretations of Alibi, not exact views of the venue.</p><p>Photos and can artwork were sourced from Alibi’s website for this private concept. Public-use permissions and complete photo credits still need confirmation.</p><p><a href="${L.officialVenue}" target="_blank" rel="noopener">Alibi’s venue details ↗</a> · <a href="${L.officialMenu}" target="_blank" rel="noopener">Alibi’s menu ↗</a> · <a href="${L.events}" target="_blank" rel="noopener">Alibi’s calendar ↗</a></p></div></details></div></footer></body></html>`;
}
