import { esc, icon } from './components.mjs';
const nav = [['/menu/','Menu'],['/whats-on/',"What's on"],['/visit/','Visit']];
export function layout({site,page,title,description,main,head=''}) {
 const L=site.links;
 return `<!doctype html><html lang="en" data-page="${page}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#F6F2E8"><title>${esc(title==='Home'?'Alibi Incline Public House':title+' · Alibi Incline Public House')}</title><meta name="description" content="${esc(description)}"><link rel="icon" href="/assets/favicon.png"><link rel="preload" href="/assets/fonts/fraunces-soft.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/fonts/dm-sans-var.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/site.css"><link rel="stylesheet" href="/assets/desktop.css" media="screen and (min-width: 1000px)"><link rel="stylesheet" href="/assets/house-shell.css">${head}<script src="/assets/site.js" defer></script><script src="/assets/desktop-story.js" defer></script></head><body data-page="${page}"><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><a class="brand${page==='home'?' brand-type':''}" href="/" aria-label="Alibi Incline Public House home"><img src="/assets/svg/alibi-wordmark.svg" width="147" height="173" alt="Alibi Ale Works"><span>INCLINE<br>PUBLIC HOUSE</span></a><button class="nav-toggle" type="button" aria-label="Open navigation" aria-expanded="false" aria-controls="site-nav">Menu ${icon('menu')}</button><nav id="site-nav" aria-label="Main navigation">${nav.map(([href,label])=>`<a href="${href}"${(page==='home'&&href==='/')||href===`/${page}/`?' aria-current="page"':''}>${label}</a>`).join('')}<a class="nav-order" href="${L.order}" target="_blank" rel="noopener">Order pizza to go ${icon('arrow-ne')}<span class="sr-only"> (opens in a new tab)</span></a></nav></header>
<main id="main">${main}</main>
<footer class="house-footer"><div class="house-footer-main"><a class="house-footer-brand" href="/" aria-label="Alibi Incline Public House home"><img src="/assets/svg/alibi-wordmark.svg" width="147" height="173" alt=""><span>Alibi<br>Incline Public House</span></a>${page==='home'?'':`<address>931 Tahoe Blvd.<br>Incline Village, NV 89451<br><a href="tel:${site.phone.tel}">${site.phone.display}</a></address>`}<nav aria-label="Footer navigation">${nav.map(([href,label])=>`<a href="${href}">${label}</a>`).join('')}</nav><a class="footer-instagram" href="${L.instagram}" target="_blank" rel="noopener">Instagram ↗<span class="sr-only"> (opens in a new tab)</span></a></div><div class="house-footer-notes"><p>A private design concept for Alibi Ale Works.</p><details class="credits"><summary>About this concept &amp; credits</summary><div><p>This is a design preview, not Alibi’s official website. For current menus, hours and events, follow the links to Alibi.</p><p>The modeled sign and beer-world illustrations are artistic interpretations, not exact views of the venue.</p><p>Photos and can artwork were sourced from Alibi’s website for this private concept. Public-use permissions and complete photo credits still need confirmation.</p><p><a href="${L.officialVenue}" target="_blank" rel="noopener">Alibi’s venue details ↗</a> · <a href="${L.officialMenu}" target="_blank" rel="noopener">Alibi’s menu ↗</a> · <a href="${L.events}" target="_blank" rel="noopener">Alibi’s calendar ↗</a></p></div></details></div></footer></body></html>`;
}
