import {picture,esc,dateParts} from './components.mjs';
import {houseCopy as copy,houseLink as link,closure} from './house-components.mjs';
import {upcoming,closures} from './event-rows.mjs';
import {isFresh,freshnessAttrs,hoursChecked} from './hero-today.mjs';
const image=(key,alt,sizes='100vw',max=1400,priority=false)=>picture(key,{alt,sizes,max,priority});
const kitchen='Kitchen closes at 9pm. Last to-go order at 8:45pm.';
const dishes=items=>`<dl class="house-dishes">${items.map(d=>`<div><dt>${esc(d.name)}</dt>${d.desc?`<dd>${esc(d.desc)}</dd>`:''}${d.note?`<dd class="dish-qualification">${esc(d.note)}</dd>`:''}</div>`).join('')}</dl>`;
const sectionLink=(id,text)=>`<a href="#${id}">${text}</a>`;

export function menuPage({site,menu,events,today}){
 const [beers,na,cocktails,wine,bottles]=menu.drinks;
 const practical=freshnessAttrs(hoursChecked(site,events),today,events.staleAfterDays);
 const schedule=freshnessAttrs([menu.scheduleChecked||menu.checked,events.exceptionsChecked].sort()[0],today,events.staleAfterDays);
 return `<div class="house-route menu-route">${closure(today)}
 <section class="route-opening" aria-labelledby="menu-title"><h1 id="menu-title">Food and drink</h1><div class="route-opening-details"><p ${practical}>${kitchen}</p><div>${link(site.links.officialMenu,'Open the full menu',{external:true})}${link(site.links.order,'Order pizza to go',{filled:true,external:true})}</div></div></section>
 <nav class="house-menu-nav" aria-label="Menu categories">${[['food','Food'],['drinks','Beer'],['other-drinks','Other drinks'],['happy-hour','Happy hour'],['brunch','Brunch']].map(([id,text])=>sectionLink(id,text)).join('')}</nav>
 <figure class="menu-opening-image">${image('pizza-and-pints','Pizza and Alibi pints on a wooden table.','100vw',1920,true)}</figure>
 <section class="route-section menu-selection" id="food" aria-labelledby="food-title"><div class="route-section-heading"><h2 id="food-title">A few from the menu</h2><div><p>Menu selection recorded September 26, 2026.</p>${link(site.links.officialMenu,'Open the full menu',{external:true})}</div></div>
 ${menu.food.map((c,i)=>`<section class="house-menu-category" id="${esc(c.id)}" aria-labelledby="${esc(c.id)}-title"><div><h3 id="${esc(c.id)}-title">${esc(c.title)}</h3>${c.intro?`<p>${esc(c.intro)}</p>`:''}</div>${dishes(c.items)}</section>${i===1?`<div class="menu-photo-pair"><figure>${image('food-bao','Pork belly bao with pickled vegetables.','(min-width:1000px) 45vw, 90vw',1200)}<figcaption>Pork Belly Bao</figcaption></figure><figure>${image('food-salad','A salad with greens and vegetables.','(min-width:1000px) 30vw, 67vw',1000)}<figcaption>Salad</figcaption></figure></div>`:''}`).join('')}
 </section>
 <section class="route-section menu-beer" id="drinks" aria-labelledby="beer-title"><div class="route-section-heading"><h2 id="beer-title">Beer</h2>${link(site.links.beers,'See the beer menu',{external:true})}</div><div class="menu-beer-layout"><figure>${image('tap-pour','An Alibi bartender pouring a pint.','(min-width:1000px) 30vw, 60vw',1000)}</figure><div><dl class="house-beer-list">${copy.beers.items.map(b=>`<div><dt>${esc(b.name)}</dt><dd>${esc(b.style)}</dd><dd>${esc(b.line)}</dd>${b.id==='contradiction'?'<dd class="dish-qualification">Contains lactose.</dd>':''}</div>`).join('')}</dl><p class="route-fine">A few from our beer lineup. For the current selection, open Alibi's menu.</p>${link(site.links.officialMenu,'Open the full menu',{external:true})}</div></div></section>
 <section class="route-section other-drinks" id="other-drinks" aria-labelledby="other-drinks-title"><div class="route-section-heading"><h2 id="other-drinks-title">Other drinks</h2></div>${[na,cocktails].map(c=>`<section class="house-menu-category" id="${esc(c.id)}" aria-labelledby="${esc(c.id)}-title"><div><h3 id="${esc(c.id)}-title">${esc(c.title)}</h3></div>${dishes(c.items)}</section>`).join('')}<section class="house-menu-category" id="wine" aria-labelledby="wine-title"><div><h3 id="wine-title">Wine</h3></div><div class="wine-selection">${wine.groups.map(g=>`<div><h4>${esc(g.label)}</h4><ul>${g.items.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></div>`).join('')}</div></section></section>
 <section class="route-section menu-times" aria-label="Happy hour and brunch"><section id="happy-hour" aria-labelledby="happy-hour-title"><h2 id="happy-hour-title">Happy hour</h2><p ${schedule}>Monday to Friday, 3pm to 5pm. Excludes holiday periods.</p><div class="menu-time-columns"><div><h3>Snacks</h3>${dishes(menu.happyHour.snacks)}</div><div><h3>Drinks</h3>${dishes(menu.happyHour.drinks)}</div></div>${link(site.links.officialMenu,'Open the full menu',{external:true})}</section><section id="brunch" aria-labelledby="brunch-title"><h2 id="brunch-title">Brunch</h2><p ${schedule}>Sunday brunch, 10am to 3pm during football season.</p>${dishes(menu.brunch.items)}${link(site.links.officialMenu,'Open the full menu',{external:true})}</section></section>
 <div class="route-end"><p ${practical}>${kitchen}</p>${link(site.links.order,'Order pizza to go',{filled:true,external:true})}</div>
 </div>`;
}

function event(e){
 const d=dateParts(e.date),cancelled=e.status==='cancelled';
 return `<li class="house-event${cancelled?' is-cancelled':''}" data-event data-date="${e.date}" data-end="${e.date}" data-checked="${e.checked}"${e.endsAt?` data-ends-at="${e.endsAt}"`:''}><time datetime="${e.date}"><span>${d.mon}</span><strong>${d.d}</strong><span>${d.dow}</span></time><div><p class="house-event-location">Incline Public House</p><h3>${esc(e.title)}</h3><p>${cancelled?'<strong>Cancelled</strong>':esc(e.time)}</p>${e.detail&&(e.special||cancelled)?`<p class="house-event-description">${esc(e.detail)}</p>`:''}</div>${link(e.url,e.action||'Event details',{external:true})}</li>`;
}
export function whatsOnPage({site,events,today}){
 const fresh=isFresh(events.checked,today,events.staleAfterDays);
 const list=fresh?upcoming(events.events,today).filter(e=>e.status!=='closure'&&isFresh(e.checked,today,events.staleAfterDays)&&(!e.endsAt||today!==new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles'}).format(new Date())||Date.now()<Date.parse(e.endsAt))):[];
 return `<div class="house-route events-route">${closure(today)}<section class="route-opening" aria-labelledby="events-title"><h1 id="events-title">What's on<br>at Incline</h1>${link(site.links.events,"Open Alibi's event calendar",{external:true})}</section><figure class="events-opening-image">${image('music-night','Live music at Alibi Incline Public House','100vw',1400,true)}</figure>
 <section class="route-section house-calendar" id="upcoming" aria-labelledby="calendar-title" data-calendar data-checked="${events.checked}" data-stale-days="${events.staleAfterDays}"><div class="route-section-heading"><h2 id="calendar-title">Upcoming events</h2><p class="route-fine">Details checked October 4, 2026.<br>Open a listing for the latest information.</p></div><ol class="house-event-list" data-event-list>${list.map(event).join('')}</ol><div data-events-stale${fresh?' hidden':''}><p>See Alibi's calendar for current events.</p></div><div data-events-empty${list.length||!fresh?' hidden':''}><p>Check Alibi's calendar for upcoming events.</p></div>${link(site.links.events,"Open Alibi's event calendar",{external:true})}</section>
 </div>`;
}
export function visitPage({site,events,today}){
 const practical=freshnessAttrs(hoursChecked(site,events),today,events.staleAfterDays);
 return `<div class="house-route visit-route">${closure(today)}<section class="route-opening" aria-labelledby="visit-title"><h1 id="visit-title">Visit Incline<br>Public House</h1><div class="route-opening-details"><address>931 Tahoe Blvd.<br>Incline Village, NV 89451</address><div>${link(site.links.directions,'Get directions',{filled:true,external:true})}${link('tel:'+site.phone.tel,'Call the pub')}</div></div></section><figure class="visit-opening-image">${image('deck','The Alibi deck, shade sails, and outdoor bar.','100vw',1920,true)}</figure>
 <section class="route-section visit-practical" id="hours" aria-labelledby="hours-title"><div class="visit-hours"><h2 id="hours-title">Regular pub hours</h2>${closure(today)}<table class="house-hours" data-hours ${practical} data-closures="${esc(JSON.stringify(closures(events.events)))}"><caption class="sr-only">Regular pub hours. Announced closures take precedence.</caption><tbody>${site.hours.map(h=>`<tr data-day="${h.short}" data-routine-hours="${h.open} to ${h.close}"><th scope="row">${h.days}</th><td>${h.open} to ${h.close}</td></tr>`).join('')}</tbody></table><p class="visit-kitchen" ${practical}>${kitchen}</p><p class="route-fine">Hours checked October 4, 2026.<br>${link(site.links.officialVenue,'Alibi’s venue details',{external:true})}</p></div><div class="visit-arrival"><h2>Getting here</h2><address>931 Tahoe Blvd.<br>Incline Village, NV 89451</address><p>Across from Raley’s, with parking on site and nearby.</p><a class="visit-phone-link" href="tel:${site.phone.tel}">${site.phone.display}</a>${link(site.links.directions,'Get directions',{external:true})}<figure>${image('sign-snow','The Alibi sign beside Tahoe Boulevard covered in winter snow.','(min-width:1000px) 38vw, 88vw',1000)}<figcaption>The sign on Tahoe Boulevard in winter.</figcaption></figure></div></section>
 <section class="route-section visit-policies" aria-labelledby="visit-policy-title"><h2 id="visit-policy-title">At the public house</h2><div><p>Families are welcome.</p><p>Leashed dogs are welcome in the Beer Forest and lower patio, but not inside.</p><p>Outdoor seating is seasonal and weather-dependent.</p></div></section>
 <section class="route-section visit-gatherings" id="gatherings" aria-labelledby="gatherings-title"><figure>${image('event-hall','Timber tables and the indoor stage in the Incline Public House event hall.','(min-width:1000px) 55vw, 88vw',1400)}</figure><div><h2 id="gatherings-title">Group events</h2><p>${esc(site.gatherings.capacity)}</p>${link(site.links.bookEvent,'Ask about a group event',{external:true})}</div></section></div>`;
}
