import { picture, btn, arrowLink, eyebrow, ext, esc } from './components.mjs';
import { upcoming, miniRow, closureNotice } from './event-rows.mjs';
import { todayStrip } from './hero-today.mjs';
export const homeHead=()=>'';
const art=(file,cls='')=>`<img class="${cls}" src="/assets/art/${file}" alt="" aria-hidden="true">`;
export function home({site,events,today}) {
 const L=site.links;
 const days=(Date.parse(today)-Date.parse(events.checked))/864e5;
 const fresh=days<=(events.staleAfterDays||14);
 const next=upcoming(events.events,today).filter(e=>!['closure','cancelled'].includes(e.status));
 const closed=events.events.filter(e=>e.status==='closure').map(e=>closureNotice(e,today)).join('');
 return `<div class="table-story" data-table-story>
<section class="home-hero" aria-labelledby="home-title"><div class="hero-copy"><p class="eyebrow">ALIBI ALE WORKS · INCLINE PUBLIC HOUSE</p><h1 id="home-title">Pull up<br>a <em>chair.</em></h1><p class="hero-lead">Pizza, house beer, and good company in Incline Village.</p><div class="actions">${btn('/menu/','See the menu',{iconName:'arrow-right'})}${arrowLink('/visit/','Plan a visit')}</div>${todayStrip({site,events,today})}</div>
<div class="hero-art" aria-hidden="true"><picture class="house-scene"><source media="(max-width: 999px)" srcset="/assets/art/phone-arrival.webp"><img src="/assets/art/house-scene.webp" width="1800" height="1200" alt="" fetchpriority="high" loading="eager"></picture><div class="invitation-origin" data-invitation-origin></div><div class="invitation-leaf invitation-left" data-leaf-left>${art('invitation-left.svg')}</div><div class="invitation-leaf invitation-right" data-leaf-right>${art('invitation-right.svg')}</div><div class="foreground-chair" data-chair>${art('foreground-chair.svg')}</div></div><div class="hero-marginalia"><a class="story-cue" href="#share">A seat. A slice. A little time. <span aria-hidden="true">↓</span></a><span class="hero-note">THE LONG TABLE AT ALIBI <span>— An illustrated invitation</span></span></div></section>
<section id="share" class="home-meal section" aria-labelledby="meal-title"><div class="container"><div class="meal-layout"><figure class="meal-figure"><div class="meal-anchor" data-meal-anchor><div class="meal-media" data-meal-media><div class="meal-clip" data-meal-clip>${picture('pizza-and-pints',{alt:'Alibi pizzas and two branded pints on a shared timber table.',sizes:'(min-width: 1000px) 62vw, 100vw',eager:true, max:1400})}</div><svg class="meal-frame" data-meal-frame viewBox="0 0 600 400" fill="none" aria-hidden="true" focusable="false"><path class="frame-outer" d="M3 5 Q111 2 224 4 L596 3 L598 395 Q478 399 351 396 L3 397 Z" stroke="#172B27"/><path class="frame-amber" d="M9 11 Q250 8 590 10 L591 388 Q380 391 10 388 Z" stroke="#C56834"/><path class="frame-detail" d="M0 399 Q219 393 599 399 M1 1 L596 0" stroke="#173E35"/></svg><div class="static-open">${art('open-invitation-static.svg')}</div></div></div><figcaption>A real meal at Alibi. Pull up a seat.</figcaption></figure><div class="meal-copy"><p class="eyebrow">FROM OUR KITCHEN, TO YOUR TABLE</p><h2 id="meal-title">Something<br>good to <em>share.</em></h2><p>Sourdough pizza, pub favorites, and another reason to stay a while.</p><p class="process-line"><a href="https://alibialeworks.com/2024/02/26/alibis-new-pizza-program-in-incline-village-lake-tahoe/" target="_blank" rel="noopener">Our pizza story starts with Truckee Sourdough Company. ↗</a></p><div class="actions">${btn('/menu/#food','Explore the food',{iconName:'arrow-right'})}${ext(L.order,'Order pickup')}</div></div></div><div class="food-details"><p class="food-aside">A few more<br>reasons to linger.</p><a class="food-detail" href="/menu/#snacks">${picture('food-bao',{alt:'Pork Belly Bao on an Alibi plate.',sizes:'(min-width: 1000px) 26vw, 45vw',max:800})}<span>Pork Belly Bao <b>↗</b></span></a><a class="food-detail" href="/menu/#greens">${picture('food-salad',{alt:'Garden Salad with bright vegetables and greens.',sizes:'(min-width: 1000px) 26vw, 45vw',max:800})}<span>Garden Salad <b>↗</b></span></a></div></div></section></div>
<section class="home-spaces section" aria-labelledby="spaces-title"><div class="container seat-layout" data-seats><div class="seat-copy"><p class="eyebrow">THREE WAYS TO SETTLE IN</p><h2 id="spaces-title">Find your<br>kind of <em>corner.</em></h2><p>Inside with the crowd, out on the deck, or among the pines.</p><div class="seat-controls" aria-label="Choose your seat">${['Inside','The deck','Beer Forest'].map((name,i)=>`<button type="button" data-seat="${i}" aria-pressed="${i===0}"><span>0${i+1}</span>${name}<b aria-hidden="true">↗</b></button>`).join('')}</div>${arrowLink('/visit/#spaces','See the house notes')}</div><div class="seat-panels">${[
 ['dining-hall','Inside','Timber beams, shared tables, and room for good company.'],
 ['deck','The deck','A heated deck, when the weather allows.'],
 ['forest-guests','Beer Forest','Our landscaped garden in the warmer months. Leashed dogs welcome here and on the lower patio.']
 ].map(([key,name,note],i)=>`<figure class="seat-panel" data-seat-panel="${i}">${picture(key,{alt:`${name} at Alibi Incline Public House.`,sizes:'(min-width: 1000px) 56vw, 100vw',max:1200})}<figcaption><strong>${name}</strong><span>${note}</span></figcaption></figure>`).join('')}</div></div></section>
<section class="home-events section"><div class="container event-layout"><figure class="company-photo">${picture('friends-dining',{alt:'Friends sharing food and pints at a timber table inside Alibi.',sizes:'(min-width: 1000px) 44vw, 100vw',max:1200})}<figcaption>Good food tastes better around a full table.</figcaption><svg class="string-lights" viewBox="0 0 600 90" aria-hidden="true"><path d="M0 8Q290 145 600 8"/>${[60,160,260,360,460,550].map((x,i)=>`<path d="M${x} ${[31,56,72,69,49,24][i]}v14"/><ellipse cx="${x}" cy="${[31,56,72,69,49,24][i]+20}" rx="5" ry="8"/>`).join('')}</svg></figure><div class="event-copy"><p class="eyebrow">MAKE AN EVENING OF IT</p><h2>Good company.<br>Good <em>plans.</em></h2><p>Talks, trivia, celebrations, and nights worth coming out for.</p>${closed}<div data-event-list data-checked="${events.checked}" data-stale-days="${events.staleAfterDays||14}" data-limit="3"><ol class="mini-events">${fresh?next.map(miniRow).join(''):''}</ol><p class="event-fallback"${fresh&&next.length?' hidden':''}>For the latest dates, see Alibi's official calendar.</p></div><div class="actions">${arrowLink('/whats-on/',"See what's on")}${ext(L.events,'Latest calendar')}</div></div></div></section>
<section class="home-beer section"><div class="container beer-layout"><div class="can-still"><div class="can-group">${[['can-kolsch','Kölsch'],['can-ipa','IPA'],['can-porter','Porter']].map(([key,name])=>`<figure>${picture(key,{alt:`Alibi ${name} can.`,sizes:'(min-width: 1000px) 170px, 28vw',max:480})}<figcaption>${name}</figcaption></figure>`).join('')}</div><svg class="table-line" viewBox="0 0 680 40" aria-hidden="true"><path d="M5 20Q140 1 310 17T675 11M30 28Q320 42 650 24"/></svg></div><div class="beer-copy"><p class="eyebrow">BREWED BY ALIBI</p><h2>Made by Alibi.<br>Best with <em>company.</em></h2><p>Explore the house beers, then ask us what's pouring today.</p><div class="actions">${btn('/menu/#drinks','Explore the drinks',{iconName:'arrow-right'})}${ext(L.beers,'Our beers')}</div></div></div></section>
<section class="home-visit section"><div class="container final-layout"><div><p class="eyebrow">COME ON OVER</p><h2>There's a place<br>for you <em>here.</em></h2><p class="visit-address">931 Tahoe Blvd.<br>Incline Village, NV 89451</p>${todayStrip({site,events,today})}<div class="actions">${btn(L.directions,'Get directions',{external:true})}${arrowLink('/visit/','Plan your visit')}</div></div>${art('closing-fragment.webp','closing-art')}</div></section>`;
}
