import { esc, icon } from './components.mjs';
const nav = [['/','Home'],['/menu/','Menu'],['/whats-on/',"What's On"],['/visit/','Visit']];
export function layout({site,page,title,description,main,head=''}) {
 const L=site.links;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#F6F2E8"><title>${esc(title==='Home'?'Pull up a chair':title)} · Alibi Incline Public House</title><meta name="description" content="${esc(description)}"><link rel="icon" href="/assets/favicon.png"><link rel="preload" href="/assets/fonts/fraunces-soft.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/fonts/dm-sans-var.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/site.css">${head}<script src="/assets/site.js" defer></script></head><body data-page="${page}"><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><a class="brand" href="/" aria-label="Alibi Incline Public House, home"><img src="/assets/svg/alibi-wordmark.svg" width="102" height="58" alt="Alibi Ale Works"><span>INCLINE<br>PUBLIC HOUSE</span></a><button class="nav-toggle" type="button" aria-expanded="false" aria-controls="site-nav">Menu ${icon('menu')}</button><nav id="site-nav" aria-label="Main navigation">${nav.map(([href,label])=>`<a href="${href}"${(page==='home'&&href==='/')||href===`/${page}/`?' aria-current="page"':''}>${label}</a>`).join('')}<a class="nav-order" href="${L.order}" target="_blank" rel="noopener">Order pickup ${icon('arrow-ne')}<span class="sr-only"> (opens in a new tab)</span></a></nav></header>
<main id="main">${main}</main>
<footer class="site-footer"><div class="footer-top container"><a href="/" class="footer-logo"><img src="/assets/svg/alibi-footer-lockup.svg" width="245" height="164" alt="Alibi Ale Works"></a><div class="footer-address"><p class="eyebrow">INCLINE PUBLIC HOUSE</p><p>931 Tahoe Blvd.<br>Incline Village, NV 89451</p><a href="tel:${site.phone.tel}">${site.phone.display}</a></div><nav aria-label="Footer navigation">${nav.map(([href,label])=>`<a href="${href}">${label}</a>`).join('')}</nav><nav aria-label="More from Alibi"><a href="${L.giftCards}" target="_blank" rel="noopener">Gift cards ↗</a><a href="${L.events}" target="_blank" rel="noopener">Official calendar ↗</a><a href="${L.newsletter}" target="_blank" rel="noopener">The Alibi newsletter ↗</a><a href="${L.instagram}" target="_blank" rel="noopener">Instagram ↗</a></nav></div><div class="footer-bottom container"><p>Independent concept demo for Alibi Ale Works.</p><details class="credits"><summary>About this demo / Credits</summary><div><p>A private design concept, not the official Alibi website. Published information is a dated snapshot; follow official links for current details.</p><p>“The Long Table at Alibi” is an original AI-assisted print illustration inspired by photographs of the actual Public House, deck and Beer Forest, with separately authored invitation and furniture details. It is an interpretation, not a documentary view.</p><p>Photography and can artwork courtesy of Alibi Ale Works. Pizza-and-pints image: Jeff Freeman (filename attribution). Pepperoni pizza: Kevin Drake. Other photographers are unconfirmed. Photos are used for this private demo; public reuse rights have not been established.</p><p><a href="${L.officialVenue}" target="_blank" rel="noopener">Venue and hours ↗</a> · <a href="${L.officialMenu}" target="_blank" rel="noopener">Published menu ↗</a> · <a href="${L.events}" target="_blank" rel="noopener">Event sources ↗</a></p></div></details></div></footer></body></html>`;
}
